export const ID = {
  GANDALF: 'gandalf',
  SAURON: 'sauron'
};
export const ATTACK = {
  ROCK: 'ATTACK_ROCK',
  PAPER: 'ATTACK_PAPER',
  SCISSORS: 'ATTACK_SCISSORS',
  LIZARD: 'ATTACK_LIZARD',
  SPOCK: 'ATTACK_SPOCK'
};

export const WINS_CHART = {
  [ATTACK.ROCK]: [ ATTACK.LIZARD, ATTACK.SCISSORS ],
  [ATTACK.PAPER]: [ ATTACK.ROCK, ATTACK.SPOCK ],
  [ATTACK.SCISSORS]: [ ATTACK.PAPER, ATTACK.LIZARD ],
  [ATTACK.LIZARD]: [ ATTACK.PAPER, ATTACK.SPOCK ],
  [ATTACK.SPOCK]: [ ATTACK.ROCK, ATTACK.SCISSORS ]
};

export const ATTACK_POINTS = {
  [ATTACK.ROCK]: 30,
  [ATTACK.PAPER]: 25,
  [ATTACK.SCISSORS]: 20,
  [ATTACK.LIZARD]: 15,
  [ATTACK.SPOCK]: 10
};

const ALIASES_GANDALF = {
  [ATTACK.ROCK]: 'Hobbit',
  [ATTACK.PAPER]: 'Magic',
  [ATTACK.SCISSORS]: 'Eagle',
  [ATTACK.LIZARD]: 'Elfs',
  [ATTACK.SPOCK]: 'Friendship'
};
const ALIASES_SAURON = {
  [ATTACK.ROCK]: 'Ring',
  [ATTACK.PAPER]: 'Ghosts',
  [ATTACK.SCISSORS]: 'Orks',
  [ATTACK.LIZARD]: 'Smaug',
  [ATTACK.SPOCK]: 'Darkness'
};
export const ATTACK_ALIAS = {
  [ID.GANDALF]: ALIASES_GANDALF,
  [ID.SAURON]: ALIASES_SAURON
};
